server:
  port: 8002

spring:
  application:
    name: employee-service
  cloud:
    config:
      enabled: false

# config: 
#  import: optional:configserver:http://localhost:8088/

eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

management:
  tracing:
    sampling:
     probability: 1.0   